apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: secret-echo-workflow
  namespace: ci
spec:
  schedule: "0 * * * *"
  ## 既存のジョブが実行中の場合に新しいジョブを開始するか。"Allow", "Forbid", "Replace" が選べる
  ## Allow（デフォルト）：CronJobは同時に実行するジョブを許可
  ## Forbid：同時に実行は許可しない。
  ## Replace：前のジョブがまだ終了していない時はそのジョブはキャンセルし、次のジョブが実行。
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0 # スケジュール時間を過ぎてからジョブが開始できる最大時間（秒）。0は制限なし
  workflowSpec: # ここにWorkflowのspecを配置。
    serviceAccountName: input-script-echo-sa
    entrypoint: secret-echo-template
    arguments:
      parameters:
      - name: message
        value: this is input message from Workflow  # Workflowから渡す値
    volumes:  ## workflowから渡す
    - name: secret
      secret:
        secretName: ci-test-secret
    templates:
    - name: secret-echo-template
      steps:
      - - name: execute-secret-echo-template
          templateRef:
            name: secret-echo ## template名
            template: steps ## templateのtemplates名

