apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: secret-echo
  namespace: ci
spec:
##  serviceAccountName: input-script-echo-sa ## ここに書いてもworkflow実行時に使われない
  entrypoint: steps
  arguments:
    parameters:
    - name: message
##      value: this is input message  ## valueはWorkflowから渡す
##  volumes:  ## volumesもworkflowから渡す
##  - name: secret
##    secret:
##      secretName: ci-test-secret
  templates:
    - name: steps
      steps:
        - - name: step1
            template: secret-echo-from-alpine
        - - name: step2
            template: secret-echo-from-ubuntu
            arguments:
              parameters:
              - name: message
                value: "{{steps.step1.outputs.result}}"

    - name: secret-echo-from-alpine
      script:
        image: alpine
        command:
          - ash
        source: |
          echo "{{workflow.parameters.message}}"

    - name: secret-echo-from-ubuntu
      inputs:
        parameters:
        - name: message
      script:
        image: ubuntu
        command:
          - bash
        source: |
          echo "{{inputs.parameters.message}}"
          ls /tmp/mount
          cat /tmp/mount/secret1
        volumeMounts:
        - name: secret
          mountPath: /tmp/mount
