apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: secret-echo-workflow-
  namespace: ci
spec:
  serviceAccountName: input-script-echo-sa
  entrypoint: secret-echo-template
  arguments:
    parameters:
    - name: message
      value: this is input message from Workflow  # Workflowから渡す値
  volumes:  ## workflowから渡す
  - name: secret
    secret:
      secretName: ci-test-secret
  templates:
  - name: secret-echo-template
    steps:
    - - name: execute-secret-echo-template
        templateRef:
          name: secret-echo
          template: steps
