package workflowtemplates _argoprojio


type WorkflowTemplateSpecTemplateDefaultsDataSourceArtifactPathsHttpAuthClientCert struct {
	ClientCertSecret *WorkflowTemplateSpecTemplateDefaultsDataSourceArtifactPathsHttpAuthClientCertClientCertSecret `field:"optional" json:"clientCertSecret" yaml:"clientCertSecret"`
	ClientKeySecret *WorkflowTemplateSpecTemplateDefaultsDataSourceArtifactPathsHttpAuthClientCertClientKeySecret `field:"optional" json:"clientKeySecret" yaml:"clientKeySecret"`
}

