package workflowtemplates _argoprojio


type WorkflowTemplateSpecTemplateDefaultsDagTasksHooksArgumentsArtifactsArtifactGcStrategy string

const (
	// OnWorkflowCompletion.
	WorkflowTemplateSpecTemplateDefaultsDagTasksHooksArgumentsArtifactsArtifactGcStrategy_ON_WORKFLOW_COMPLETION WorkflowTemplateSpecTemplateDefaultsDagTasksHooksArgumentsArtifactsArtifactGcStrategy = "ON_WORKFLOW_COMPLETION"
	// OnWorkflowDeletion.
	WorkflowTemplateSpecTemplateDefaultsDagTasksHooksArgumentsArtifactsArtifactGcStrategy_ON_WORKFLOW_DELETION WorkflowTemplateSpecTemplateDefaultsDagTasksHooksArgumentsArtifactsArtifactGcStrategy = "ON_WORKFLOW_DELETION"
	// Never.
	WorkflowTemplateSpecTemplateDefaultsDagTasksHooksArgumentsArtifactsArtifactGcStrategy_NEVER WorkflowTemplateSpecTemplateDefaultsDagTasksHooksArgumentsArtifactsArtifactGcStrategy = "NEVER"
)

