package workflowtemplates _argoprojio


type WorkflowTemplateSpecTemplateDefaultsResourceManifestFromArtifactHttpAuthClientCert struct {
	ClientCertSecret *WorkflowTemplateSpecTemplateDefaultsResourceManifestFromArtifactHttpAuthClientCertClientCertSecret `field:"optional" json:"clientCertSecret" yaml:"clientCertSecret"`
	ClientKeySecret *WorkflowTemplateSpecTemplateDefaultsResourceManifestFromArtifactHttpAuthClientCertClientKeySecret `field:"optional" json:"clientKeySecret" yaml:"clientKeySecret"`
}

