package workflowtemplates _argoprojio


type WorkflowTemplateSpecTemplatesDagTasksHooksArgumentsArtifactsHttpAuthClientCert struct {
	ClientCertSecret *WorkflowTemplateSpecTemplatesDagTasksHooksArgumentsArtifactsHttpAuthClientCertClientCertSecret `field:"optional" json:"clientCertSecret" yaml:"clientCertSecret"`
	ClientKeySecret *WorkflowTemplateSpecTemplatesDagTasksHooksArgumentsArtifactsHttpAuthClientCertClientKeySecret `field:"optional" json:"clientKeySecret" yaml:"clientKeySecret"`
}

