package workflowtemplates _argoprojio


type WorkflowTemplateSpecTemplateDefaultsDagTasksHooksArgumentsArtifactsHttpAuthClientCert struct {
	ClientCertSecret *WorkflowTemplateSpecTemplateDefaultsDagTasksHooksArgumentsArtifactsHttpAuthClientCertClientCertSecret `field:"optional" json:"clientCertSecret" yaml:"clientCertSecret"`
	ClientKeySecret *WorkflowTemplateSpecTemplateDefaultsDagTasksHooksArgumentsArtifactsHttpAuthClientCertClientKeySecret `field:"optional" json:"clientKeySecret" yaml:"clientKeySecret"`
}

