package workflowtemplates _argoprojio


type WorkflowTemplateSpecTemplateDefaultsInputsArtifactsArtifactGcStrategy string

const (
	// OnWorkflowCompletion.
	WorkflowTemplateSpecTemplateDefaultsInputsArtifactsArtifactGcStrategy_ON_WORKFLOW_COMPLETION WorkflowTemplateSpecTemplateDefaultsInputsArtifactsArtifactGcStrategy = "ON_WORKFLOW_COMPLETION"
	// OnWorkflowDeletion.
	WorkflowTemplateSpecTemplateDefaultsInputsArtifactsArtifactGcStrategy_ON_WORKFLOW_DELETION WorkflowTemplateSpecTemplateDefaultsInputsArtifactsArtifactGcStrategy = "ON_WORKFLOW_DELETION"
	// Never.
	WorkflowTemplateSpecTemplateDefaultsInputsArtifactsArtifactGcStrategy_NEVER WorkflowTemplateSpecTemplateDefaultsInputsArtifactsArtifactGcStrategy = "NEVER"
)

