package workflowtemplates _argoprojio


type WorkflowTemplateSpecTemplateDefaultsDagTasksArgumentsArtifactsArtifactGcStrategy string

const (
	// OnWorkflowCompletion.
	WorkflowTemplateSpecTemplateDefaultsDagTasksArgumentsArtifactsArtifactGcStrategy_ON_WORKFLOW_COMPLETION WorkflowTemplateSpecTemplateDefaultsDagTasksArgumentsArtifactsArtifactGcStrategy = "ON_WORKFLOW_COMPLETION"
	// OnWorkflowDeletion.
	WorkflowTemplateSpecTemplateDefaultsDagTasksArgumentsArtifactsArtifactGcStrategy_ON_WORKFLOW_DELETION WorkflowTemplateSpecTemplateDefaultsDagTasksArgumentsArtifactsArtifactGcStrategy = "ON_WORKFLOW_DELETION"
	// Never.
	WorkflowTemplateSpecTemplateDefaultsDagTasksArgumentsArtifactsArtifactGcStrategy_NEVER WorkflowTemplateSpecTemplateDefaultsDagTasksArgumentsArtifactsArtifactGcStrategy = "NEVER"
)

