package cronworkflow _argoprojio


type CronWorkflowSpecWorkflowSpecTemplateDefaultsResourceManifestFromArtifactArtifactGcStrategy string

const (
	// OnWorkflowCompletion.
	CronWorkflowSpecWorkflowSpecTemplateDefaultsResourceManifestFromArtifactArtifactGcStrategy_ON_WORKFLOW_COMPLETION CronWorkflowSpecWorkflowSpecTemplateDefaultsResourceManifestFromArtifactArtifactGcStrategy = "ON_WORKFLOW_COMPLETION"
	// OnWorkflowDeletion.
	CronWorkflowSpecWorkflowSpecTemplateDefaultsResourceManifestFromArtifactArtifactGcStrategy_ON_WORKFLOW_DELETION CronWorkflowSpecWorkflowSpecTemplateDefaultsResourceManifestFromArtifactArtifactGcStrategy = "ON_WORKFLOW_DELETION"
	// Never.
	CronWorkflowSpecWorkflowSpecTemplateDefaultsResourceManifestFromArtifactArtifactGcStrategy_NEVER CronWorkflowSpecWorkflowSpecTemplateDefaultsResourceManifestFromArtifactArtifactGcStrategy = "NEVER"
)

