package cronworkflow _argoprojio


type CronWorkflowSpecWorkflowSpecTemplatesResourceManifestFromArtifactArtifactGcStrategy string

const (
	// OnWorkflowCompletion.
	CronWorkflowSpecWorkflowSpecTemplatesResourceManifestFromArtifactArtifactGcStrategy_ON_WORKFLOW_COMPLETION CronWorkflowSpecWorkflowSpecTemplatesResourceManifestFromArtifactArtifactGcStrategy = "ON_WORKFLOW_COMPLETION"
	// OnWorkflowDeletion.
	CronWorkflowSpecWorkflowSpecTemplatesResourceManifestFromArtifactArtifactGcStrategy_ON_WORKFLOW_DELETION CronWorkflowSpecWorkflowSpecTemplatesResourceManifestFromArtifactArtifactGcStrategy = "ON_WORKFLOW_DELETION"
	// Never.
	CronWorkflowSpecWorkflowSpecTemplatesResourceManifestFromArtifactArtifactGcStrategy_NEVER CronWorkflowSpecWorkflowSpecTemplatesResourceManifestFromArtifactArtifactGcStrategy = "NEVER"
)

