package cronworkflow _argoprojio


type CronWorkflowSpecWorkflowSpecTemplatesDagTasksArgumentsArtifactsArtifactGcStrategy string

const (
	// OnWorkflowCompletion.
	CronWorkflowSpecWorkflowSpecTemplatesDagTasksArgumentsArtifactsArtifactGcStrategy_ON_WORKFLOW_COMPLETION CronWorkflowSpecWorkflowSpecTemplatesDagTasksArgumentsArtifactsArtifactGcStrategy = "ON_WORKFLOW_COMPLETION"
	// OnWorkflowDeletion.
	CronWorkflowSpecWorkflowSpecTemplatesDagTasksArgumentsArtifactsArtifactGcStrategy_ON_WORKFLOW_DELETION CronWorkflowSpecWorkflowSpecTemplatesDagTasksArgumentsArtifactsArtifactGcStrategy = "ON_WORKFLOW_DELETION"
	// Never.
	CronWorkflowSpecWorkflowSpecTemplatesDagTasksArgumentsArtifactsArtifactGcStrategy_NEVER CronWorkflowSpecWorkflowSpecTemplatesDagTasksArgumentsArtifactsArtifactGcStrategy = "NEVER"
)

