package cronworkflow _argoprojio


type CronWorkflowSpecWorkflowSpecArgumentsArtifactsArtifactGcStrategy string

const (
	// OnWorkflowCompletion.
	CronWorkflowSpecWorkflowSpecArgumentsArtifactsArtifactGcStrategy_ON_WORKFLOW_COMPLETION CronWorkflowSpecWorkflowSpecArgumentsArtifactsArtifactGcStrategy = "ON_WORKFLOW_COMPLETION"
	// OnWorkflowDeletion.
	CronWorkflowSpecWorkflowSpecArgumentsArtifactsArtifactGcStrategy_ON_WORKFLOW_DELETION CronWorkflowSpecWorkflowSpecArgumentsArtifactsArtifactGcStrategy = "ON_WORKFLOW_DELETION"
	// Never.
	CronWorkflowSpecWorkflowSpecArgumentsArtifactsArtifactGcStrategy_NEVER CronWorkflowSpecWorkflowSpecArgumentsArtifactsArtifactGcStrategy = "NEVER"
)

