package workflows_argoprojio


type WorkflowSpecTemplateDefaultsDagTasksHooksArgumentsArtifactsArtifactGcStrategy string

const (
	// OnWorkflowCompletion.
	WorkflowSpecTemplateDefaultsDagTasksHooksArgumentsArtifactsArtifactGcStrategy_ON_WORKFLOW_COMPLETION WorkflowSpecTemplateDefaultsDagTasksHooksArgumentsArtifactsArtifactGcStrategy = "ON_WORKFLOW_COMPLETION"
	// OnWorkflowDeletion.
	WorkflowSpecTemplateDefaultsDagTasksHooksArgumentsArtifactsArtifactGcStrategy_ON_WORKFLOW_DELETION WorkflowSpecTemplateDefaultsDagTasksHooksArgumentsArtifactsArtifactGcStrategy = "ON_WORKFLOW_DELETION"
	// Never.
	WorkflowSpecTemplateDefaultsDagTasksHooksArgumentsArtifactsArtifactGcStrategy_NEVER WorkflowSpecTemplateDefaultsDagTasksHooksArgumentsArtifactsArtifactGcStrategy = "NEVER"
)

