package workflows_argoprojio


type WorkflowSpecTemplateDefaultsDagTasksHooksArgumentsArtifactsHttpAuthClientCert struct {
	ClientCertSecret *WorkflowSpecTemplateDefaultsDagTasksHooksArgumentsArtifactsHttpAuthClientCertClientCertSecret `field:"optional" json:"clientCertSecret" yaml:"clientCertSecret"`
	ClientKeySecret *WorkflowSpecTemplateDefaultsDagTasksHooksArgumentsArtifactsHttpAuthClientCertClientKeySecret `field:"optional" json:"clientKeySecret" yaml:"clientKeySecret"`
}

