package workflows_argoprojio


type WorkflowSpecTemplateDefaultsInputsArtifactsArtifactGcStrategy string

const (
	// OnWorkflowCompletion.
	WorkflowSpecTemplateDefaultsInputsArtifactsArtifactGcStrategy_ON_WORKFLOW_COMPLETION WorkflowSpecTemplateDefaultsInputsArtifactsArtifactGcStrategy = "ON_WORKFLOW_COMPLETION"
	// OnWorkflowDeletion.
	WorkflowSpecTemplateDefaultsInputsArtifactsArtifactGcStrategy_ON_WORKFLOW_DELETION WorkflowSpecTemplateDefaultsInputsArtifactsArtifactGcStrategy = "ON_WORKFLOW_DELETION"
	// Never.
	WorkflowSpecTemplateDefaultsInputsArtifactsArtifactGcStrategy_NEVER WorkflowSpecTemplateDefaultsInputsArtifactsArtifactGcStrategy = "NEVER"
)

