apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: configmap-echo-
  namespace: ci
spec:
  serviceAccountName: input-script-echo-sa
  entrypoint: steps
  arguments:
    parameters:
    - name: message
      value: this is input message
  volumes:  # 追加
  - name: configmap
    configMap:
      name: ci-test-configmap
  templates:
    - name: steps
      steps:
        - - name: step1
            template: configmap-echo-from-alpine
        - - name: step2
            template: configmap-echo-from-ubuntu
            arguments:
              parameters:
              - name: message
                value: "{{steps.step1.outputs.result}}"

    - name: configmap-echo-from-alpine
      script:
        image: alpine
        command:
          - ash
        source: |
          echo "{{workflow.parameters.message}}"

    - name: configmap-echo-from-ubuntu
      inputs:
        parameters:
        - name: message
      script:
        image: ubuntu
        command:
          - bash
        source: |
          echo "{{inputs.parameters.message}}"
          ls /tmp/mount
          cat /tmp/mount/key1
        volumeMounts:  # 追加
        - name: configmap
          mountPath: /tmp/mount

