## kubectl apply -f でapplyする
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-world-sa
  namespace: ci

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: input-script-echo-sa
  namespace: ci

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ci
  name: pod-patch-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-patch-role-binding
  namespace: ci
subjects:
- kind: ServiceAccount
  name: input-script-echo-sa
  namespace: ci
roleRef:
  kind: Role
  name: pod-patch-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ci-test-configmap
  namespace: ci
data:
  key1: "value1"
  key2: "value2"
  key3: "value3"

---
apiVersion: v1
kind: Secret
metadata:
  name: ci-test-secret
  namespace: ci
type: Opaque
stringData:
  secret1: secret_value1 # 文字列データ
  secret2: secret_value2 # 文字列データ
  secret3: secret_value3 # 文字列データ
