package workflowtemplates_argoprojio


type WorkflowTemplateSpecTemplatesResourceManifestFromArtifactArtifactGcStrategy string

const (
	// OnWorkflowCompletion.
	WorkflowTemplateSpecTemplatesResourceManifestFromArtifactArtifactGcStrategy_ON_WORKFLOW_COMPLETION WorkflowTemplateSpecTemplatesResourceManifestFromArtifactArtifactGcStrategy = "ON_WORKFLOW_COMPLETION"
	// OnWorkflowDeletion.
	WorkflowTemplateSpecTemplatesResourceManifestFromArtifactArtifactGcStrategy_ON_WORKFLOW_DELETION WorkflowTemplateSpecTemplatesResourceManifestFromArtifactArtifactGcStrategy = "ON_WORKFLOW_DELETION"
	// Never.
	WorkflowTemplateSpecTemplatesResourceManifestFromArtifactArtifactGcStrategy_NEVER WorkflowTemplateSpecTemplatesResourceManifestFromArtifactArtifactGcStrategy = "NEVER"
)

