package workflowtemplates_argoprojio


type WorkflowTemplateSpecTemplateDefaultsResourceManifestFromArtifactHttpAuthBasicAuth struct {
	PasswordSecret *WorkflowTemplateSpecTemplateDefaultsResourceManifestFromArtifactHttpAuthBasicAuthPasswordSecret `field:"optional" json:"passwordSecret" yaml:"passwordSecret"`
	UsernameSecret *WorkflowTemplateSpecTemplateDefaultsResourceManifestFromArtifactHttpAuthBasicAuthUsernameSecret `field:"optional" json:"usernameSecret" yaml:"usernameSecret"`
}

