package workflowtemplates_argoprojio


type WorkflowTemplateSpecTemplatesDataSourceArtifactPathsArtifactGcStrategy string

const (
	// OnWorkflowCompletion.
	WorkflowTemplateSpecTemplatesDataSourceArtifactPathsArtifactGcStrategy_ON_WORKFLOW_COMPLETION WorkflowTemplateSpecTemplatesDataSourceArtifactPathsArtifactGcStrategy = "ON_WORKFLOW_COMPLETION"
	// OnWorkflowDeletion.
	WorkflowTemplateSpecTemplatesDataSourceArtifactPathsArtifactGcStrategy_ON_WORKFLOW_DELETION WorkflowTemplateSpecTemplatesDataSourceArtifactPathsArtifactGcStrategy = "ON_WORKFLOW_DELETION"
	// Never.
	WorkflowTemplateSpecTemplatesDataSourceArtifactPathsArtifactGcStrategy_NEVER WorkflowTemplateSpecTemplatesDataSourceArtifactPathsArtifactGcStrategy = "NEVER"
)

