package workflowtemplates_argoprojio


type WorkflowTemplateSpecTemplatesResourceManifestFromArtifactHttpAuthClientCert struct {
	ClientCertSecret *WorkflowTemplateSpecTemplatesResourceManifestFromArtifactHttpAuthClientCertClientCertSecret `field:"optional" json:"clientCertSecret" yaml:"clientCertSecret"`
	ClientKeySecret *WorkflowTemplateSpecTemplatesResourceManifestFromArtifactHttpAuthClientCertClientKeySecret `field:"optional" json:"clientKeySecret" yaml:"clientKeySecret"`
}

