package cronworkflow_argoprojio


type CronWorkflowSpecWorkflowSpecTemplatesResourceManifestFromArtifactHttpAuthClientCert struct {
	ClientCertSecret *CronWorkflowSpecWorkflowSpecTemplatesResourceManifestFromArtifactHttpAuthClientCertClientCertSecret `field:"optional" json:"clientCertSecret" yaml:"clientCertSecret"`
	ClientKeySecret *CronWorkflowSpecWorkflowSpecTemplatesResourceManifestFromArtifactHttpAuthClientCertClientKeySecret `field:"optional" json:"clientKeySecret" yaml:"clientKeySecret"`
}

