package cronworkflow_argoprojio


type CronWorkflowSpecWorkflowSpecTemplateDefaultsInputsArtifactsHttpAuthClientCert struct {
	ClientCertSecret *CronWorkflowSpecWorkflowSpecTemplateDefaultsInputsArtifactsHttpAuthClientCertClientCertSecret `field:"optional" json:"clientCertSecret" yaml:"clientCertSecret"`
	ClientKeySecret *CronWorkflowSpecWorkflowSpecTemplateDefaultsInputsArtifactsHttpAuthClientCertClientKeySecret `field:"optional" json:"clientKeySecret" yaml:"clientKeySecret"`
}

