package cronworkflow_argoprojio


type CronWorkflowSpecWorkflowSpecTemplateDefaultsOutputsArtifactsHttpAuthClientCert struct {
	ClientCertSecret *CronWorkflowSpecWorkflowSpecTemplateDefaultsOutputsArtifactsHttpAuthClientCertClientCertSecret `field:"optional" json:"clientCertSecret" yaml:"clientCertSecret"`
	ClientKeySecret *CronWorkflowSpecWorkflowSpecTemplateDefaultsOutputsArtifactsHttpAuthClientCertClientKeySecret `field:"optional" json:"clientKeySecret" yaml:"clientKeySecret"`
}

