package cronworkflow_argoprojio


type CronWorkflowSpecWorkflowSpecTemplateDefaultsDataSourceArtifactPathsHttpAuthBasicAuth struct {
	PasswordSecret *CronWorkflowSpecWorkflowSpecTemplateDefaultsDataSourceArtifactPathsHttpAuthBasicAuthPasswordSecret `field:"optional" json:"passwordSecret" yaml:"passwordSecret"`
	UsernameSecret *CronWorkflowSpecWorkflowSpecTemplateDefaultsDataSourceArtifactPathsHttpAuthBasicAuthUsernameSecret `field:"optional" json:"usernameSecret" yaml:"usernameSecret"`
}

