package cronworkflow_argoprojio


type CronWorkflowSpecWorkflowSpecTemplatesDataSourceArtifactPathsHttpAuthClientCert struct {
	ClientCertSecret *CronWorkflowSpecWorkflowSpecTemplatesDataSourceArtifactPathsHttpAuthClientCertClientCertSecret `field:"optional" json:"clientCertSecret" yaml:"clientCertSecret"`
	ClientKeySecret *CronWorkflowSpecWorkflowSpecTemplatesDataSourceArtifactPathsHttpAuthClientCertClientKeySecret `field:"optional" json:"clientKeySecret" yaml:"clientKeySecret"`
}

